$ErrorActionPreference = 'Stop'
$repo = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../..'))
$failures = [Collections.Generic.List[string]]::new()
function Check([bool]$condition, [string]$message) {
    if (!$condition) { $failures.Add($message); Write-Host "FAIL $message" } else { Write-Host "PASS $message" }
}
function Source([string]$path) {
    $full = Join-Path $repo $path
    if (!(Test-Path -LiteralPath $full)) { return '' }
    return [IO.File]::ReadAllText($full)
}
$effect = Source 'SteriaBuild/FarAreaEffect_Steria_OceanWave.cs'
$driver = Source 'SteriaBuild/SlazeyaStormVisualController.cs'
$card = Source 'SteriaBuild/CardAbilities.cs'
$ability = [regex]::Match($card, '(?s)public class DiceCardSelfAbility_SlazeyaMassAttackTeamLightGain.*?(?=// --- Slazeya Dice Abilities ---)').Value
$builder = Source 'SteriaBuild/VFXSource/SlazeyaStormMass/UnityProject/Assets/Editor/SlazeyaStormMassBundleBuilder.cs'
$shader = Source 'SteriaBuild/VFXSource/SlazeyaStormMass/UnityProject/Assets/Shaders/SlazeyaStormFlow.shader'
$cloudShader = Source 'SteriaBuild/VFXSource/SlazeyaStormMass/UnityProject/Assets/Shaders/SlazeyaStormCloud.shader'
$volumeShader = Source 'SteriaBuild/VFXSource/SlazeyaStormMass/UnityProject/Assets/Shaders/SlazeyaStormCloudVolume.shader'
$densitySource = Source 'SteriaBuild/VFXSource/SlazeyaStormMass/UnityProject/Assets/Shaders/SlazeyaStormCloudDensity.cginc'
$cloudNoise = Source 'SteriaBuild/VFXSource/SlazeyaStormMass/UnityProject/Assets/Shaders/SlazeyaStormCloudNoise.cginc'
$particleShader = Source 'SteriaBuild/VFXSource/SlazeyaStormMass/UnityProject/Assets/Shaders/SlazeyaStormParticles.shader'
$lightningShader = Source 'SteriaBuild/VFXSource/SlazeyaStormMass/UnityProject/Assets/Shaders/SlazeyaStormLightning.shader'
$build = Source 'SteriaBuild/VFXSource/SlazeyaStormMass/build_slazeya_storm_bundle.ps1'
Check ($effect -notmatch 'override\s+bool\s+(HasIndependentAction|ActionPhase)|\.GiveDamage\(|\.TakeDamage\(|OnEndFarAreaBehaviourAtk\(') 'default manager owns damage and defense'
Check ($effect -match 'override void GiveDamageFromManager' -and $effect -match '_burstTriggered' -and $effect -notmatch 'damagedUnitList\.Count') 'callback permits empty victims and locks duplicate burst'
Check ($effect -notmatch 'if\s*\(\s*!isRunning\s*\)\s*return') 'tail continues after gathering gate opens'
Check ($effect -match 'isRunning = true' -and $driver -match 'GatherDuration = 1.35f' -and $driver -match 'TailDuration = 1.20f') 'R5 frozen gate and tail durations'
Check ($effect -match 'IsBreakLifeZero\(' -and $effect -match 'IsKnockout\(' -and $effect -match 'CallbackWatchdog' -and $effect -match 'manager.attacker != _self') 'cancellation and bounded callback wait'
Check ($effect -match 'Singleton<BattleFarAreaPlayManager>.Instance' -and $effect -match 'manager.victims' -and $effect -match 'GetAliveList_opponent\(self.faction\)' -and $effect -match 'unit.faction != self.faction') 'current opposing recipients without fixed faction'
Check ($effect -match 'SpriteRenderer' -and $effect -match 'bounds' -and $driver -match 'FitFootprint' -and $driver -match 'normalizedRadius') 'rendered body bounds and corner-covering XZ ellipse'
Check ($ability -notmatch 'CreateOceanWaveEffect|OceanWaveEffectComponent|AddScreenShake' -and $ability -match 'flowConsumedByThisCard / 8' -and $ability -match 'PrimalTidePowerScope.RunWithAllowance') 'remove only duplicate visual; preserve Flow power'
Check ($driver -match 'sealed class SlazeyaStormVisualController\s*:\s*IDisposable' -and $driver -notmatch ':\s*MonoBehaviour') 'canonical plain C# controller'
Check (([regex]::Matches($driver, '\.Simulate\(').Count -eq 1) -and $driver -match '\.Simulate\(deltaTime, false, false, false\)' -and $driver -notmatch '\.Play\(') 'single non-recursive explicit simulation path, no autoplay'
Check ($driver -match 'MaterialPropertyBlock' -and $driver -match '"_Phase"' -and $shader -notmatch '_Time|GrabPass|ZTest Always') 'explicit phase and normal scene depth'
Check ($shader -match 'Shader "Steria/SlazeyaStormFlow"' -and $shader -match 'ZWrite Off') 'fixed supported shader contract'
Check ($builder -match 'AssetBundle.LoadFromFile' -and $builder -match 'new SlazeyaStormVisualController' -and $builder -notmatch 'AddComponent<SlazeyaStormVisualController>') 'bundle readback drives actual shared controller'
Check ($build -match 'Get-FileHash' -and $build -match 'SHA256' -and $build -match 'WindowStyle Hidden' -and $build -notmatch '-nographics|git commit|Copy-Item.*SteriaModFolder') 'isolated hash-checked build without deployment'
Check ($builder -notmatch 'Length == 5|particles.Length == 3|budget <= 160|maximumAlive <= 160|MakeTexture\(|Mesh Ribbon\(') 'old count restrictions and striped ribbon generation removed'
Check ($driver -match 'EnvelopeCenter' -and $driver -match 'EnvelopeRadii' -and $driver -match 'Bounds\[\] bodyBounds' -and $driver -match '0.81f') 'shared all-body sample envelope with 0.90 margin'
Check ($driver -notmatch '_bubble' -and $builder -notmatch 'MakeBubbleSurface' -and $driver -match 'CloudInnerRadii' -and $builder -match 'VerifyCloudRing') 'open cloud hole replaces closed shell and bottom cap rendering'
Check ($driver -match 'CloudInitialPosition' -and $driver -match 'CloudForward' -and $driver -match 'CollapseOffset') 'same persistent cloud identities actually collapse into a filled core'
Check ($driver -match 'FoamParcelPosition' -and $driver -match 'UpdateFoamParcels' -and $driver -match 'SetParticles\(_foamParcels' -and $builder -match 'VerifyFoamTransport') 'persistent native foam positions and readback convergence check'
Check ($shader -match '_Collapse' -and $shader -match 'CorePoint' -and $shader -match 'ExpandedRingPoint' -and $driver -match 'WaveProgress' -and $driver -match 'CollapseOffset') 'same finite core and continuous circumferential wavefront on CPU and GPU'
Check ($shader -match 'BubbleNormal' -and $shader -match '_NormalRoughness') 'finite ellipsoid / deformed smooth normal, including pole'
Check ($shader -match 'Blend One OneMinusSrcAlpha' -and $shader -match 'color \* alpha') 'single premultiplied transparent water body'
Check ($builder -match 'water_body_rgba.png' -and $builder -match 'water_normal_roughness.png' -and $builder -match 'water_flow_rg.png' -and $builder -match 'foam_spray_4x4.png' -and $builder -match 'mist_density_lighting_4x4.png' -and $builder -match 'droplet_spindrift_4x2.png') 'six frozen texture worker assets imported, no substitute textures'
Check ($driver -match '_burstPhase' -and $driver -match 'CoreCenter' -and $driver -match 'WaveProgress' -and $driver -match 'RingNormal' -and $driver -match 'RingTangent') 'core-origin burst inherits captured phase and ellipse-normal momentum'
Check ($builder -match 'burstAge' -and $builder -match 'round5' -and $build -match 'LastWriteTimeUtc') 'R5 output, callback-relative samples, fresh log validation'
Check ($driver -match 'CrestLiftMist' -and $driver -match '_primaryReturnReleased' -and $driver -match '_secondaryReturnReleased') 'crest mist and two finite return clusters'
Check ($driver -match 't>=0.05f' -and $driver -match '0.10f' -and $lightningShader -match 'Steria/SlazeyaStormLightning' -and $lightningShader -notmatch '_Time|ZTest Always') 'two bounded local discharges with dark interval'
Check ($particleShader -match 'alpha=data.a\*_Alpha;' -and $particleShader -notmatch 'data.a\*data.r' -and $builder -match 'color.enabled=!mist') 'authored mist alpha once, no repeated density/lifetime fade'
Check ($cloudShader -match 'Steria/SlazeyaStormCloud' -and $cloudNoise -match 'cloudFbm' -and $cloudNoise -match 'valueNoise' -and $cloudShader -match 'opticalCoverage\*i.color.a\*_Alpha' -and $cloudShader -match 'opticalDepth=-log' -and $cloudShader -notmatch 'data.a\*data.a' -and $cloudShader -notmatch '_Time|GrabPass|ZTest Always') 'independent cloud shader consumes per-card alpha once and advects spatial multiscale density'
Check ($cloudShader -match 'min\(5.999,seed\*6\)' -and $builder -match 'VerifyCloudFrames' -and $builder -match 'GetCurrentSize3D') 'fixed complete cloud frames and full nonuniform card support diagnostics'
Check ($volumeShader -match 'unity_OrthoParams' -and $volumeShader -match 'localDirection' -and $volumeShader -match 'step<1024' -and $volumeShader -match 'lightIndex<132' -and $volumeShader -match 'transmission<0.02' -and $densitySource -match 'return float2\(density,density\)' -and $volumeShader -notmatch '_Time|GrabPass|ZTest Always|CameraDepthTexture') 'bounded full-box volume rays, one density integral and density shadows'
Check ($volumeShader -match 'outerLength=core.x' -and $volumeShader -match 'cursor\+=lightStep' -and $volumeShader -match 'SampleCloudDensity\(p,lightStep\).x' -and $volumeShader -match 'clamp\(_LightSteps,48,96\)' -and $volumeShader -match 'innerCount' -and $volumeShader -notmatch 'lightIndex<3|_LocalScale\*0.24') 'outer light integral reaches box exit with separately refined core segments'
Check ($driver -match 'MacroPose' -and $driver -match 'CloudSourceMaxRadius' -and $builder -match 'CaptureMacroViews' -and $builder -match 'Macro full corner' -and $builder -match 'GetComponentsInChildren<Collider>') 'real visual-only macro meshes, standalone evidence and finite core corner support'
Check ($densitySource -match '0.30\*\(1-length' -and $densitySource -match '0.090\*\(2\*shapeTex.g-1\)' -and $densitySource -match '0.060\*\(2\*shapeTex.b-1\)' -and $densitySource -match '0.025\*\(2\*shapeTex.a-1\)' -and $densitySource -match '0.035\*\(1-detail\)' -and $densitySource -notmatch 'edgeBand|signedSupport|thinEdge|inverse\*inverse|baseDensity<0.70') 'approved continuous physical-distance multilevel lobes and independent detail, no protected smooth belly'
Check ($volumeShader -match 'fixedStep=_CloudHeight/clamp\(_StepsPerH,16,96\)' -and $volumeShader -match 'boundary-cursor' -and $volumeShader -match 'lightTransmission\(samplePosition,sigma\)' -and $volumeShader -notmatch 'step%4|targetLight|pow\(light,1.25\)|_SigmaT\*_ExtinctionScale' -and $densitySource -match 'CloudPhaseHG') 'reference-H outer step, exact interval boundaries and local-only extinction compensation'
Check ($builder -match 'SlazeyaStormCloudNoiseBaker.Ensure' -and $builder -match 'SlazeyaStormCloudNoiseBaker.VerifyBundle' -and $builder -match 'CaptureDensitySlice' -and $builder -match '_DebugTransmittance' -and $build -match 'CloudShape64.asset') 'frozen baker API binding, numerical Bundle verification and runtime slice/T evidence'
Check ($driver -match 'MacroCount=1' -and $driver -match 'CloudSinkTravel' -and $driver -match 'BuildSinkCurve' -and $driver -notmatch 'CloudUniformScale' -and $driver -match 'CloudContainerPose' -and $builder -match 'PrimitiveType.Cube\);var mesh' -and $volumeShader -match 'outerBudget' -and $cloudNoise -match '2.4\+0.7\*sin\(3\*theta\)' -and $cloudNoise -match 'float J=\(r/r0\)\*radial\*sy' -and $densitySource -match 'cloudSinkInverse') 'cached monotone cylindrical transport and gradient-aware bounded integration; no uniform scale delivery'
Check ($driver -match 'root==null&&footprint.Height==0&&footprint.CloudInnerRadii.x==0&&footprint.CloudInnerRadii.y==0' -and $driver -match '_sinkValues=new float\[6\];_sinkTangents=new float\[6\]' -and $driver -match 'BuildSinkCurve\(footprint,out _sinkValues,out _sinkTangents,out _sourceRadiusQuantiles\);if\(root==null\)return') 'empty-geometry null-root fallback has a zero curve; valid missing-prefab geometry remains strictly validated'
$cpuCompact = $driver -replace '\s',''
$gpuCompact = $shader -replace '\s',''
Check ($cpuCompact.Contains('width=0.11f+0.45f*strength+0.02f*Mathf.Sin(theta*11)') -and $gpuCompact.Contains('width=0.11+0.45*strength+0.02*sin(theta*11)') -and $cpuCompact.Contains('crest=0.20f*strength') -and $gpuCompact.Contains('crest=0.20*strength')) 'R6 frozen CPU/GPU width and crest formulas'
Check ($gpuCompact.Contains('survival=1-ease((_BurstAge-0.24-0.12*ringStrength)/0.28)')) 'R6 bounded ring survival without global alpha changes'
Check ($driver -match '_secondJetReleased=new bool\[SectorCount\]' -and $cpuCompact.Contains('0.07f+0.025f*Hash(i,41)') -and $driver -match 'EmitSecondSector' -and $cpuCompact.Contains('if(_burstAge<0.16f)EmitSecondSector(i)')) 'R6 independent finite second sector locks and stale-window guard'
Check ($cpuCompact.Contains('strength>0.12f') -and $cpuCompact.Contains('2+Mathf.RoundToInt(strength*5)') -and $cpuCompact.Contains('10000+sector*32') -and $driver -match 'bool second=false') 'R6 second batch quantity and isolated seed range; original spray default unchanged'
Check ($driver -match '_waterfallReleased=new bool\[4\]' -and $cpuCompact.Contains('0.06f+i*0.06f') -and $cpuCompact.Contains('if(_burstAge<0.30f)EmitWaterfallStreaks(i)') -and $cpuCompact.Contains('batch*64+lobe*12+j') -and $cpuCompact.Contains('lobe==3?4:8') -and $cpuCompact.Contains('(j+Hash(seed,71))/count-0.5f')) 'R6 four finite stratified waterfall batches, no cross-batch seed collision'
Check ($builder -match '"BurstDroplets",drops,320,true' -and $builder -match '"WaterfallStreaks",gatheredFoam,128,true' -and $builder -match '"BurstDroplets"\?2125u:name=="WaterfallStreaks"\?2017u' -and $builder -match 'lengthScale=3.35f' -and $builder -match 'if\(name=="WaterfallStreaks"\)main.startSize3D=true' -and $driver -match 'streak.startSize3D=new Vector3\(width,length,1\)' -and $driver -match 'longCount=lobe==3\?1:\(\(batch\+lobe\)%3==0\?3:2\)') 'R6 capacity/seeds and approved 32 long / 80 short independently sized native streaks'
Check ($builder -match 'VerifyBurstAbundance' -and $builder -match 'VerifyGpuWavefront' -and $builder -match 'maximumAlive<=640') 'R6 native emission totals, pool headroom, and actual GPU wavefront checks'
Check ($build -match 'PreviewDirectory' -and $build -match 'FirstCandidate' -and $build -match 'Reviewed' -and $builder -match '-previewDirectory') 'R6 unique CLI preview path and first-candidate versus reviewed gates'
if ($failures.Count) { throw "Slazeya storm source verification failed: $($failures.Count) contract(s)." }
Write-Host 'Slazeya storm focused source verification PASS'
